InventoryTrackerGroup4/GroupFourPhaseOne/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GroupFourPhaseOne.Controllers
{   // This is the AdminController it returns the views specific to the admin pages such as adminhome and adminIndex.
    // This page is authorized and may only be viewed by users that have logged in.

    [Authorize]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult AdminIndex()
        {
            return View();
        }

        public ActionResult AdminHome()
        {
            return View();
        }
    }
}

InventoryTrackerGroup4/GroupFourPhaseOne/Controllers/LoginController.cs
using GroupFourPhaseOne.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Helpers;


// Creates a cookie to authorize users
// References logout
// Compares login credentials to what is in the database
// Verifies Crypto.HashPasswords

namespace GroupFourPhaseOne.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]

        public ActionResult LogIn(User user)

        {

            //if (ModelState.IsValid)

            //{

            if (IsValid(user.Username, user.Password))

            {

                FormsAuthentication.SetAuthCookie(user.Username, false);

                return RedirectToAction("AdminHome", "Admin");

            }

            else

            {

                ModelState.AddModelError("", "Username or Password is incorrect.");

            }
            return View(user);

        }



        public ActionResult LogOut()

        {

            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");

        }

        private bool IsValid(string Username, string Password)

        {


            bool IsValid = false;



            using (var db = new InventoryTrackerDatabase())

            {

                var user = db.Users.FirstOrDefault(u => u.Username == Username);

                if (user != null)

                {

                    if (Crypto.VerifyHashedPassword(user.Password, Password))

                    {

                        IsValid = true;

                    }

                }

            }

            return IsValid;

        }
    }
}


        

InventoryTrackerGroup4/GroupFourPhaseOne/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GroupFourPhaseOne.Models;
using System.Web.Helpers;

namespace GroupFourPhaseOne.Controllers
{
    // This is the user Controller, it allows an admin to View, Create, Edit, and Delete Users to and from the database from the webpage.
    // This page is authorized and may only be viewed by users that have logged in.
    [Authorize]
    public class UserController : Controller
    {
        private InventoryTrackerDatabase db = new InventoryTrackerDatabase();

        // GET: User
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // This method allows an admin to create a User and store it in the database.
        // This method also Crypto.HashPassword Passwords
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,FirstName,LastName,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Password = Crypto.HashPassword(user.Password);
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,FirstName,LastName,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InventoryTrackerGroup4/GroupFourPhaseOne/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inventory Tracker", "AdminHome", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Admin Home", "AdminHome", "Admin", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Inventory Manager","AdminIndex", "Admin", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Users", "Index", "User", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Logout", "LogOut", "Login", new { area = "" }, null)</li>
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year<br /> CMPS 383 project: Phase one, Group four</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

InventoryTrackerGroup4/GroupFourPhaseOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
 


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inventory Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Login", "LogIn", "Login", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Inventory", "Inventory", "Inventory", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Basket", "Basket", "Basket", new { area = "" }, null)</li>
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year<br /> CMPS 383 project: Phase one, Group four</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>